config/routes.rb
Rails.application.routes.draw do
 devise_for :users

  require 'sidekiq/web'
  mount Sidekiq::Web=> '/sidekiq'
  
  root to: 'pages#index'
  get '/pages/:task_type', to: 'pages#sorted', as: 'sorted'
  get '/help', to: 'pages#help'

  get '/report/index', to: 'reports#index'
  get '/report', to: 'reports#new'
  patch '/report:id', to: 'reports#update', as: 'report_answer'
  post '/report', to: 'reports#create'
  get '/admin_pages/admin_main', to: 'admin_pages#admin_main'

  get '/users/index', to: 'users#index'
  get '/users/:id', to: 'users#user_info', as: 'users'
  get '/users/edit/:id', to: 'users#edit', as: 'edit_user'
  patch '/users/edit/:id/', to: 'users#update', as: 'user_update'


  get '/tasks/new', to: 'tasks#new'
  get '/tasks/:id', to: 'tasks#task_info', as: 'tasks'
  post '/tasks/new', to: 'tasks#create' 
  post '/tasks/:id' , to: 'tasks#perform', as: 'perform_task'

  

   #root 'pages#main'
  # get '/register', to: 'devise/registrations#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  validates :text, presence: true , length: { maximum: 55}
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  enum task_type: [:like, :subscribe, :comment]
  enum status: [:active,:finished,:rejected]

  validates :task_url, presence: true, length: { maximum: 55 }
  validates :description, presence: true, length: { maximum: 55 } 
  validates :goal, presence: true
  validates :goal, numericality: {greater_than_or_equal_to: 0}
  validates :task_url, presence: true
  validates :amount, numericality: {greater_than_or_equal_to: 0}
  validate  :enough_balance?

  private

  def enough_balance?
    #binding.pry
  	if (user.balance >= (user.tasks.where(status: "active").sum(:amount) + amount))&& amount > 0
  	  true
  	else
  	  errors.add(:amount, "Not enough money, silly boy")
      false
  	end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  #mount_uploader :avatar, AvatarUploader

  enum role: [:user, :admin]
  has_many :tasks
  has_many :user_tasks
  has_many :reports
  #has_one_attached :avatar, styles: { thumb: "100x100>" }

  #validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  validates :first_name, :last_name, :nick_name, presence: true
  validates :first_name, :last_name, :nick_name, length: { maximum: 15 }

end

app/models/user_task.rb
class UserTask < ApplicationRecord
	enum status: [:started, :done, :rejected]
	belongs_to :task
	belongs_to :user

	validates_uniqueness_of :task, scope: :user

end

app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController
  before_action :authenticate_user!
	def main
      authorize(current_user)
	end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :nick_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :nick_name])

  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource)
    your_new_after_confirmation_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	#before_action :authenticate_user!, except: [:index, :help]

    # get actions
	def index
	   only_avalible
	end

	def help
	end

	def sorted
	  @tasks = only_avalible.where(task_type: params[:task_type])
	end

	# post actions

	private

	def only_avalible
	  if current_user
		started_tasks_id = UserTask.where(user_id: current_user.id, status: "started").pluck(:task_id)
		@tasks = Task.where.not(id: started_tasks_id).where(status: 'active')
	  else
	  	@tasks = Task.where(status: 'active')
	  end
	end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	before_action :authenticate_user!
	before_action :admin_check!, except: [:create, :new]

    def new
	end
   
	def create # post
		current_user.reports.create(report_params)
		redirect_to root_path
	end

	def update # patch
		Report.find(params[:id]).update(answer)
	end

	def index 
		@reports= Report.where(answer: nil)
	end

	private

	def answer 
		params.require(:report).permit(:answer)
	end

	def report_params
	    params.require(:report).permit(:user_id, :text)
	end

	 def admin_check!
	    authorize current_user
	 end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!, except: [:task_info]
	def task_info
	  @task= task  #in private method you will see
	end

	def perform
	  if task_avalible? 
		  User.find(current_user.id).user_tasks.create(task_id: params[:id])
		  redirect_to "https://twitter.com/#{Task.find(params[:id]).task_url}"
	  else
	  	  redirect_to root_path
	  end
	end

	def new # view, GET
	end

	def create
		task = current_user.tasks.create(task_params)
		redirect_to root_path
	end

	private

	def task
	  Task.find(params[:id])
	end

	def task_avalible?
	   if task.goal.eql?(task.completed)
	   	 task.update(status: "finished")
	   	 false
	   else
	   	 true
	   end
	end

	def task_params
	    params.require(:task).permit(:description, :goal, :task_type, :task_url, :amount)
	end

end



#Remember
 #render json: {errors: task.errors}

app/controllers/user_controller.rb
class UserController < ApplicationController
	before_action :admin_check!
  def index
  	@users = User.all
  end

  def delete
  	#User.delete.where(params)
  end

  private

   def admin_check!
	 unless current_user and current_user.admin?
    	redirect_to root_path
     end
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
	before_action :admin_check!, except: [:add_balance]
  

  def index
  	@users = User.all
  end

  def user_info
     @user = user
  end

  def edit # get
     @user = user
  end

  def update # patch
     user.update(user_params)
  end

  private

  def user
    User.find(params[:id])
  end

  def user_params
     params.require(:user).permit(:first_name, :nick_name, :last_name, :role, :balance, :avatar)
  end

   def admin_check!
     authorize current_user
   end
end

app/helpers/admin_pages_helper.rb
module AdminPagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/completed_tasks_helper.rb
module CompletedTasksHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin_pages/admin_main.html.erb
<p1> Secret Page! Only for admins </p1>
<li><%= link_to 'All Users', users_index_path %></li>
<li><%= link_to 'All Reports', report_index_path %></li>

app/views/reports/index.html.erb
<h4>All report's, ser. Will you answer on them?</h4>
<% if @reports %> 
	<% @reports.each do |report| %>
		From: <%= report.user.nick_name %><br>
		Text: <%= report.text %><br>
		<%= form_for :report, url: report_answer_path(report.id), method: :patch do |f| %> 
			Answer: <%= f.text_area :answer %> 
			<%= f.submit 'Save Answer' %>
		<% end %>
		<p>_____________________________________</p>
	<%end%>
<% else %>
	<p> ..no reports </p>
<% end %>

app/views/reports/new.html.erb
<p> Form for reports</p>
<%= form_for :report do |f| %> <br>
Can i help you? <%= f.text_field :text %> <br>
<%= f.submit 'Done' %>
<% end %>
<p>______________________</p>

<p>Answers to you:</p>
<% if current_user %>
	<%= current_user.reports.where.not(answer: nil).each do |report| %>
		Your question: <%= report.text %> <br>
		Answer: <%= report.answer %> <br><br>
	<% end %>
<% else %>
	<p> ..empty </p>
<% end %>

app/views/tasks/new.html.erb
<h4> Enter information about your Task and then Confirm </h4>
<%= form_for :task do |f| %> <br>
I need: <%= f.text_field :goal %> <%= f.select(:task_type, [ 'like', 'subscribe' ]) %>'s <br>
Link: twitter.com/<%= f.text_field :task_url %> <br>
Budget:      <%=f.text_field :amount %> <br>
Description: <%= f.text_area :description %> <br>
<%= f.submit %>
<% end %>

app/views/tasks/task_info.html.erb
<p class='center'> Hello! Here your can see information about this task! </p>
<br>
<ol>
<p> Description: <br> <%= @task.description %>
<p> We need <%= @task.goal %> <%= @task.task_type %>'s
<br> And already have <%= @task.completed %> </p>
</ol>
<% if current_user %>
  <li ><%= link_to 'Perform this Task' , perform_task_path(@task.id), method: :post %> </li>
  <% end %>

app/views/user/index.html.erb
<% @users.each do |user| %>
    <li>
        <%= link_to user.name, user_index_path %>
    </li>
<% end %>

app/views/users/edit.html.erb
<p>You are Editing user: <%= @user.nick_name %> </p>
<%= form_for :user, url: user_update_path, method: :patch do |f| %> <br> 
	New balance: <%= f.text_field :balance %> <br>
	New role: <%= f.text_field :role %> <br>
	New nick name: <%= f.text_field :nick_name %> <br>
	<%= f.submit %>
<%end%>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <li>
        <%= link_to user.first_name, users_path(user.id) %> 
    </li> 
    balance: <%= user.balance %> <br><br>
<% end %>

app/views/users/user_info.html.erb
<% if current_user.id == @user.id %>
	<h4> My account: </h4>
	<% else %>
	<h4> User info: </h4>
<%end%>
<p> id: <%= @user.id %> </p>
<p> Nick: <%= @user.nick_name %> </p>
<p> First name: <%= @user.first_name %> ,  Last name: <%= @user.last_name %> <p> 
<p> Balance: <%= @user.balance %> </p>
<p> Done tasks: <%= @user.user_tasks.where(status: 'done').count %>
<% if current_user.id == @user.id %>
	<li><%= link_to 'Top up my balance(closed for now)', "#"%></li>
	<li><%=link_to 'Edit account', edit_user_registration_path%></li>
<%elsif current_user.admin?%>
	<li><%=link_to 'Edit user account', edit_user_path%></li>
<%end%>