config/routes.rb
Rails.application.routes.draw do
 devise_for :users

  require 'sidekiq/web'
  mount Sidekiq::Web=> '/sidekiq'
  
  root to: 'pages#index'
  get '/pages/:task_type', to: 'pages#sorted', as: 'sorted'
  get '/help', to: 'pages#help'

  get '/report/index', to: 'reports#index'
  get '/report', to: 'reports#new'
  patch '/report:id', to: 'reports#update', as: 'report_answer'
  post '/report', to: 'reports#create'
  get '/admin_pages/admin_main', to: 'admin_pages#admin_main'

  get '/users/index', to: 'users#index'
  get '/users/:id', to: 'users#user_info', as: 'users'
  get '/users/edit/:id', to: 'users#edit', as: 'edit_user'
  patch '/users/edit/:id/', to: 'users#update', as: 'user_update'


  get '/tasks/new', to: 'tasks#new'
  get '/tasks/:id', to: 'tasks#task_info', as: 'tasks'
  post '/tasks/new', to: 'tasks#create' 
  post '/tasks/:id' , to: 'tasks#perform', as: 'perform_task'

  

   #root 'pages#main'
  # get '/register', to: 'devise/registrations#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  validates :text, presence: true , length: { maximum: 55}
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  enum task_type: [:like, :subscribe, :comment]
  enum status: [:active,:finished,:rejected]

  validates :task_url, presence: true, length: { maximum: 55 }
  validates :description, presence: true, length: { maximum: 55 } 
  validates :goal, presence: true
  validates :goal, numericality: {greater_than_or_equal_to: 0}
  validates :task_url, presence: true
  validates :amount, numericality: {greater_than_or_equal_to: 0}
  validate  :enough_balance?

  private

  def enough_balance?
    #binding.pry
  	if (user.balance >= (user.tasks.where(status: "active").sum(:amount) + amount))&& amount > 0
  	  true
  	else
  	  errors.add(:amount, "Not enough money, silly boy")
      false
  	end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  #mount_uploader :avatar, AvatarUploader

  enum role: [:user, :admin]
  has_many :tasks
  has_many :user_tasks
  has_many :reports
  #has_one_attached :avatar, styles: { thumb: "100x100>" }

  #validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  validates :first_name, :last_name, :nick_name, presence: true
  validates :first_name, :last_name, :nick_name, length: { maximum: 15 }

end

app/models/user_task.rb
class UserTask < ApplicationRecord
	enum status: [:started, :done, :rejected]
	belongs_to :task
	belongs_to :user

	validates_uniqueness_of :task, scope: :user

end

app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController
  before_action :authenticate_user!
	def main
      authorize(current_user)
	end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :nick_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :nick_name])

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	#before_action :authenticate_user!, except: [:index, :help]

    # get actions
	def index
	   only_avalible
	end

	def help
	end

	def sorted
	  @tasks = only_avalible.where(task_type: params[:task_type])
	end

	# post actions

	private

	def only_avalible
	  if current_user
		started_tasks_id = UserTask.where(user_id: current_user.id, status: "started").pluck(:task_id)
		@tasks = Task.where.not(id: started_tasks_id).where(status: 'active')
	  else
	  	@tasks = Task.where(status: 'active')
	  end
	end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	before_action :authenticate_user!
	before_action :admin_check!, except: [:create, :new]

    def new
	end
   
	def create # post
		current_user.reports.create(report_params)
		redirect_to root_path
	end

	def update # patch
		Report.find(params[:id]).update(answer)
	end

	def index 
		@reports= Report.where(answer: nil)
	end

	private

	def answer 
		params.require(:report).permit(:answer)
	end

	def report_params
	    params.require(:report).permit(:user_id, :text)
	end

	 def admin_check!
	    authorize current_user
	 end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!, except: [:task_info]
	def task_info
	  @task= task  #in private method you will see
	end

	def perform
	  if task_avalible? 
		  User.find(current_user.id).user_tasks.create(task_id: params[:id])
		  redirect_to "https://twitter.com/#{Task.find(params[:id]).task_url}"
	  else
	  	  redirect_to root_path
	  end
	end

	def new # view, GET
	end

	def create
		task = current_user.tasks.create(task_params)
		redirect_to root_path
	end

	private

	def task
	  Task.find(params[:id])
	end

	def task_avalible?
	   if task.goal.eql?(task.completed)
	   	 task.update(status: "finished")
	   	 false
	   else
	   	 true
	   end
	end

	def task_params
	    params.require(:task).permit(:description, :goal, :task_type, :task_url, :amount)
	end

end



#Remember
 #render json: {errors: task.errors}

app/controllers/user_controller.rb
class UserController < ApplicationController
	before_action :admin_check!
  def index
  	@users = User.all
  end

  def delete
  	#User.delete.where(params)
  end

  private

   def admin_check!
	 unless current_user and current_user.admin?
    	redirect_to root_path
     end
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
	before_action :admin_check!, except: [:add_balance]
  

  def index
  	@users = User.all
  end

  def user_info
     @user = user
  end

  def edit # get
     @user = user
  end

  def update # patch
     user.update(user_params)
  end

  private

  def user
    User.find(params[:id])
  end

  def user_params
     params.require(:user).permit(:first_name, :nick_name, :last_name, :role, :balance, :avatar)
  end

   def admin_check!
     authorize current_user
   end
end

app/helpers/admin_pages_helper.rb
module AdminPagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/completed_tasks_helper.rb
module CompletedTasksHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "I want  some Likes or Subscribes!(click)", tasks_new_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Call back", report_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<%= image_tag('logo.jpg', class: "logo")%>
<%= link_to ' Ready?! Earn Money', root_path, class: 'logo_text' %>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
    </div>
    <div id="navbar">
    <ul class="nav navbar-nav pull-right">
      <li><% link_to 'Home', root_path %></li>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.decorate.name, users_path(current_user.id) %></li><br> Balance: <%= current_user.balance%> $ <br>
          Avalible: <%=current_user.decorate.avalible%> $
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
          <% if current_user.admin? %>
	        <li><%= link_to 'Admin Room', admin_pages_admin_main_path %></li>
	      <% end %>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'layouts/header' %>
  <body>
    <%= yield %>
  </body>
  <footer class= 'footer'>
   <%= render 'layouts/footer' %>
   </footer>
</html>

app/views/pages/help.html.erb
<p> Hi! Here is you can Make some Money on doing Likes or Subscribes on tweets account</p>
<p> And also gets some for Youself, just follow the instruction below: </p>

app/views/pages/index.html.erb
<h4> This is all tasks for today!</h4> 
 <%= form_for :task, url: '#', method: :get do |f| %>
	Sort by:<%= f.select(:task_type, [ 'like', 'subscribe' ]) %>
	<%= f.submit 'Find'%>
	<%end%> <br>
<ol>
<% if @tasks %>
	<% @tasks.each do |task| %>
	       Description: <%= link_to task.description, tasks_path(task.id) %> <br>
	       Type: <%= task.task_type %>'s <br>
	        Budget: <%= task.amount%> $ <br><br>
	     </ul>
	<% end %>
<% else %>
<p> Good job! That's all for this moment, see You later! </p>
<% end %>
</ol>

app/views/pages/sorted.html.erb
<h4> Here is all the results: </h4> 
<ol>
<% if @tasks %>
	<% @tasks.each do |task| %>
	       Description: <%= link_to task.description, tasks_path(task.id) %> <br>
	       Type: <%= task.task_type %>'s <br>
	       Budget: <%= task.amount%> $ <br><br>
	<% end %>
<% else %>
<p> You make them all! </p>
<% end %>
</ol>